import 'package:ssb_log_app/model/fighter.dart';

const Map<String, Fighter> Fighters = {
  "1": Fighter(id: "1", name: "マリオ"),
  "2": Fighter(id: "2", name: "ドンキーコング"),
  "3": Fighter(id: "3", name: "リンク"),
  "4": Fighter(id: "4", name: "サムス"),
  "4d": Fighter(id: "4d", name: "ダークサムス"),
  "5": Fighter(id: "5", name: "ヨッシー"),
  "6": Fighter(id: "6", name: "カービィ"),
  "7": Fighter(id: "7", name: "フォックス"),
  "8": Fighter(id: "8", name: "ピカチュウ"),
  "9": Fighter(id: "9", name: "ルイージ"),
  "10": Fighter(id: "10", name: "ネス"),
  "11": Fighter(id: "11", name: "キャプテンファルコン"),
  "12": Fighter(id: "12", name: "プリン"),
  "13": Fighter(id: "13", name: "ピーチ"),
  "13d": Fighter(id: "13d", name: "デイジー"),
  "14": Fighter(id: "14", name: "クッパ"),
  "15": Fighter(id: "15", name: "アイスクライマー"),
  "16": Fighter(id: "16", name: "シーク"),
  "17": Fighter(id: "17", name: "ゼルダ"),
  "18": Fighter(id: "18", name: "ドクターマリオ"),
  "19": Fighter(id: "19", name: "ピチュー"),
  "20": Fighter(id: "20", name: "ファルコ"),
  "21": Fighter(id: "21", name: "マルス"),
  "21d": Fighter(id: "21d", name: "ルキナ"),
  "22": Fighter(id: "22", name: "こどもリンク"),
  "23": Fighter(id: "23", name: "ガノンドロフ"),
  "24": Fighter(id: "24", name: "ミュウツー"),
  "25": Fighter(id: "25", name: "ロイ"),
  "25d": Fighter(id: "25d", name: "クロム"),
  "26": Fighter(id: "26", name: "Mr.ゲーム&ウォッチ"),
  "27": Fighter(id: "27", name: "メタナイト"),
  "28": Fighter(id: "28", name: "ピット"),
  "28d": Fighter(id: "28d", name: "ブラックピット"),
  "29": Fighter(id: "29", name: "ゼロスーツサムス"),
  "30": Fighter(id: "30", name: "和莉緒"),
  "31": Fighter(id: "31", name: "スネーク"),
  "32": Fighter(id: "32", name: "アイク"),
  "33-35": Fighter(id: "33", name: "ポケモントレーナー"),
  "36": Fighter(id: "36", name: "ディディーコング"),
  "37": Fighter(id: "37", name: "リュカ"),
  "38": Fighter(id: "38", name: "ソニック"),
  "39": Fighter(id: "39", name: "デデデ"),
  "40": Fighter(id: "40", name: "ピクミン&オリマー"),
  "41": Fighter(id: "41", name: "ルカリオ"),
  "42": Fighter(id: "42", name: "ロボット"),
  "43": Fighter(id: "43", name: "トゥーンリンク"),
  "44": Fighter(id: "44", name: "ウルフ"),
  "45": Fighter(id: "45", name: "むらびと"),
  "46": Fighter(id: "46", name: "ロックマン"),
  "47": Fighter(id: "47", name: "Wii Fit トレーナー"),
  "48": Fighter(id: "48", name: "ロゼッタ&チコ"),
  "49": Fighter(id: "49", name: "リトル・マック"),
  "50": Fighter(id: "50", name: "ゲッコウガ"),
  "51": Fighter(id: "51", name: "Miiファイター 格闘"),
  "52": Fighter(id: "52", name: "Miiファイター 剣術"),
  "53": Fighter(id: "53", name: "Miiファイター 射撃"),
  "54": Fighter(id: "54", name: "パルテナ"),
  "55": Fighter(id: "55", name: "パックマン"),
  "56": Fighter(id: "56", name: "ルフレ"),
  "57": Fighter(id: "57", name: "シュルク"),
  "58": Fighter(id: "58", name: "クッパJr."),
  "59": Fighter(id: "59", name: "ダックハント"),
  "60": Fighter(id: "60", name: "リュウ"),
  "60d": Fighter(id: "60d", name: "ケン"),
  "61": Fighter(id: "61", name: "クラウド"),
  "62": Fighter(id: "62", name: "カムイ"),
  "63": Fighter(id: "63", name: "ベヨネッタ"),
  "64": Fighter(id: "64", name: "インクリング"),
  "65": Fighter(id: "65", name: "リドリー"),
  "66": Fighter(id: "66", name: "シモン"),
  "66d": Fighter(id: "66d", name: "リヒター"),
  "67": Fighter(id: "67", name: "キングクルール"),
  "68": Fighter(id: "68", name: "しずえ"),
  "69": Fighter(id: "69", name: "ガオガエン"),
  "70": Fighter(id: "70", name: "パックンフラワー"),
  "71": Fighter(id: "71", name: "ジョーカー"),
  "72": Fighter(id: "72", name: "勇者"),
  "73": Fighter(id: "73", name: "バンジョー&カズーイ"),
  "74": Fighter(id: "74", name: "テリー"),
  "75": Fighter(id: "75", name: "ベレト/ベレス"),
  "76": Fighter(id: "76", name: "ミェンミェン"),
  "77": Fighter(id: "77", name: "スティーブ/アレックス"),
};
